sets:
  rogue:
    - 3531 #attack_speed? strength
    - 1107 #agility
    - 3012 #attack_power
    - 198 #crit_chance
    - 1078 #stamina
    
  mage:
    - 3531 #haste
    - 2340 #spellpower
    - 1139 #intellect
    - 3867 #hit rating
    - 198 #crit_spell?
    